services:
  - type: web
    name: cuetube
    runtime: docker
    plan: free # or your preferred plan
    preDeployCommand: /app/bin/migrate
    envVars:
      - key: PHX_SERVER
        value: 'true'
      - key: PHX_HOST
        sync: false
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: BASE_URL
        sync: false
    healthCheckPath: /
